services:
  container:
    image: crm/api-publisher-consumer:latest
    container_name: crm-api-publisher-consumer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9966:9966"
    restart: unless-stopped
    volumes:
      - ~/logs/crm:/var/logs