name: Deploy to Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted]
    environment: dev
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USER: ${{ secrets.SSH_USER }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PORT: ${{ secrets.SSH_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if latest image exists
        id: check_latest_image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            if docker image inspect crm/api-publisher-consumer:latest &> /dev/null;
            then
              echo "::set-output name=image_exists::'true'"
            else  
              echo "::set-output name=image_exists::'false'"
            fi

      - name: Backup previous state
        if: steps.check_latest_image.outputs.image_exists == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ~/TestServer/crm/crm-api
            docker tag crm/api-publisher-consumer:latest crm/api-publisher-consumer:backup

      - name: Deploy new version
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ~/TestServer/crm/crm-api
            docker compose down
            git checkout dev
            git pull
            docker compose up -d

      - name: Check deployment status
        uses: appleboy/ssh-action@master
        id: check_status
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ~/TestServer/crm/crm-api
            docker compose ps | grep crm-api-publisher-consumer

      - name: Rollback on failure
        if: steps.check_status.outcome != 'success'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          password: ${{ env.SSH_PASSWORD }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          port: ${{ env.SSH_PORT }}
          script: |
            cd ~/TestServer/crm/crm-api
            docker-compose down
            docker run -d --name restored_container crm/api-publisher-consumer:backup
            docker compose up -d