name: Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/github_actions

      - name: SSH into dev VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/TestServer/crm/crm-api
            git pull
            docker-compose up -d
