name: Deploy to Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted]
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: debug
        run: |
          echo ${{ secrets.SH_HOST }}
          echo ${{ secrets.SSH_USER }}
          echo ${{ secrets.SSH_PASSWORD }}
          echo ${{ secrets.SSH_PRIVATE_KEY }}
          echo ${{ secrets.SSH_PORT }}

      - name: SSH into dev VM and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/TestServer/crm/crm-api
            git checkout dev
            git pull
            docker-compose up -d